name: Publish on GitHub

on: [ workflow_dispatch ]

env:
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Run Datagen
        run: ./gradlew runDatagen

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3                                   #The specified MC-Publish GitHub Action in the version 3.2
        with:
          changelog-file: CHANGELOG.md
          github-token: "${{secrets.GITHUB_TOKEN}}"

          github-generate-changelog: true
          version-type: beta

          loaders: fabric
          java: "${{env.JAVA_VERSION}}"